<?php
$this->layout('layout::default', [
	'title' => 'Designações',
	'authentication' => isset($authentication) ? $authentication : null,
])
?>
<?php $this->start('stylesheets') ?>
<?php $this->insert('forms::designacoes-styles') ?>
<?php $this->stop() ?>

<div class="row">
	<div class="col-md-3">
		<div class="list-group">
			<a class="list-group-item" href="/">Início</a>
			<a class="list-group-item" href="/irmaos">Irmãos</a>
			<a class="list-group-item" href="/saidas">Saídas</a>
			<a class="list-group-item" href="/designacoes">Designações</a>
		</div>
	</div>
</div>

<p>
	Territórios: <?= $this->e(count($list)) ?> /
	Designações: <?= $this->e($result['count']) ?>
</p>

<?php $this->insert('forms::designacao-agrupado', [
	'list' => $list,
]) ?>

<?php /*
<ul>
foreach ($list as $designacao) {
	$this->insert('forms::designacao-linha', [
		'designacao' => $designacao,
	]);
}
</ul>
*/ ?>

<?php $this->insert('forms::designacoes', [
	'numero_territorios' => $numero_territorios,
	'irmaos' => $irmaos,
	'saidas' => $saidas,
]) ?>

<?php $this->start('javascript') ?>
<?php $this->insert('forms::designacoes-scripts') ?>
<?php $this->stop() ?>
