<?php
$this->layout('layout::default', [
    'title' => 'Irmãos - Designações',
    'authentication' => isset($authentication) ? $authentication : null,
])
?>

<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <a class="list-group-item" href="/">Início</a>
            <a class="list-group-item" href="/irmaos">Irmãos</a>
            <a class="list-group-item" href="/saidas">Saídas</a>
            <a class="list-group-item" href="/designacoes">Designações</a>
        </div>
    </div>
</div>

<?php
	$esc_id = $this->e($irmao->irmao_id);
	$esc_nome = $this->e($irmao->irmao_nome);
?>
<div class="well well-sm">
	<a href="/irmaos/editar/<?= $esc_id ?>">(editar)</a>
	<a href="/irmaos/remover/<?= $esc_id ?>">(remover)</a>
	(designações)
	(<?= $esc_id ?>) <?= $esc_nome ?>
</div>

<?php $this->insert('forms::designacao-agrupado', [
	'list' => $list,
]) ?>

<p><a href="/irmaos">Voltar para a lista</a></p>
