<?php
$this->layout('layout::default', [
    'title' => 'Saídas - Inserir',
    'authentication' => isset($authentication) ? $authentication : null,
])
?>

<div class="row">
    <div class="col-md-3">
        <div class="list-group">
            <a class="list-group-item" href="/">Início</a>
            <a class="list-group-item" href="/irmaos">Irmãos</a>
            <a class="list-group-item" href="/saidas">Saídas</a>
            <a class="list-group-item" href="/designacoes">Designações</a>
        </div>
    </div>
</div>

<p>Nova saída:</p>

<?php
	$esc_id = $this->e($saida->saida_id);
	$esc_nome = $this->e($saida->saida_nome);
?>
<p>
	<a href="/saidas/editar/<?= $esc_id ?>">(editar)</a>
	<a href="/saidas/remover/<?= $esc_id ?>">(remover)</a>
	(<?= $esc_id ?>) <?= $esc_nome ?>
</p>

<p><a href="/saidas">Voltar para a lista</a></p>
